### ISSUE TITLE
Incomplete Access model components man page 

### ISSUE THREAD

**Issue by FelixErnst** [mtmorgan/DirichletMultinomial#1]
Hi Martin,

the man page for `?mixture` and other accessors contains an incomplete second sentence.

https://github.com/mtmorgan/DirichletMultinomial/blob/d208a3b9a4a0b93f987833beeef0894b36b497ac/man/fitted.Rd#L22

Not sure, what is missing.

Felix

**Comment by FelixErnst** [comment]
`esimtated` -> `estimated`?

**Comment by FelixErnst** [comment]
@mtmorgan

**Comment by mtmorgan** [comment]
It had already been fixed https://github.com/mtmorgan/DirichletMultinomial/commit/d7b7a9a9e176aacc01e2aa2749436cca219e9dac ; a pull request fixing (only) typos in the man pages and vignettes would be welcome.
