### ISSUE TITLE
can not install DirichletMultinomial

### ISSUE THREAD

**Issue by BenxiaHu** [mtmorgan/DirichletMultinomial#4]
Hello,
    I am trying to install DirichletMultinomial via 
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("DirichletMultinomial")
```.

However, I got the following errors:
make:  [/extraspace1/Anaconda3/envs/R4.2/lib/R/etc/Makeconf:170: dirichlet_fit_main.o] Error 1
ERROR: compilation failed for package ‘DirichletMultinomial’

**Comment by mtmorgan** [comment]
Your conda environment is providing different compilation tools than your R environment; the details are in the part of the installation that you elided (`...`). Either install the package from conda (I don't know if it is available), do not use conda when installing and using this package, or provide the details of the failed compilation and we can try (it will be challenging and maybe not successful) to debug.
