### ISSUE TITLE
Cannot install DirichletMultinomial

### ISSUE THREAD

**Issue by YangLi-Bio** [mtmorgan/DirichletMultinomial#5]
Error message:

=================
Error: package or namespace load failed for ‘DirichletMultinomial’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/users/PAS1475/liyang/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-DirichletMultinomial/00new/DirichletMultinomial/libs/DirichletMultinomial.so':
  libsatlas.so.3: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
=================

The shared objects exist in my directory, and the directory has been added to LD_LIBRARY_PATH. Could you please tell me the reason?

**Comment by mtmorgan** [comment]
The problem is with libsatlas. One possibility is that you have installed the wrong 'architecture' of the library.

I do not know why you have installed this library. I have
```
DirichletMultinomial/libs# ldd DirichletMultinomial.so
	libgsl.so.23 => /lib/x86_64-linux-gnu/libgsl.so.23 (0x000000400184d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x0000004001acb000)
	libR.so => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000004001c1a000)
	libgslcblas.so.0 => /lib/x86_64-linux-gnu/libgslcblas.so.0 (0x0000004001e0c000)
	/lib64/ld-linux-x86-64.so.2 (0x0000004000000000)
```
The gsl library (and dependencies) were installed on my ubuntu system with
```
sudo apt-get install libgsl10-dev libgslcblas0
```
but the details of installation depend on your operating system. 

Without further detail I cannot be of further assistance. Perhaps there is a local technical expert that you can reach out to?

**Comment by YangLi-Bio** [comment]
Thanks for your reply.

 

Do you mean I needn’t install DirichletMultinomial.so library?

 

In addition, I have been using a High Performance Computing server and not a root user. Therefore, I cannot use sudo operation.

 

Best regards,

**Comment by mtmorgan** [comment]
Installing DirichletMultinomial requires the DirichletMultinomial.so library.

Your installation uses a non-standard 'BLAS', and DirichletMultinomial must be able to link to it.

The system administrator of your HPC cluster must have installed the non-standard BLAS, and so you should speak with them to help you install DirichletMultinomial. As you note, the key error is

```
libsatlas.so.3: cannot open shared object file: No such file or directory
```

but probably earlier there was output indicating in more detail where `libatlas` was supposed to be found.

Speak with your system administrator to help further debug this.
