### ISSUE TITLE
Keep getting NAs 

### ISSUE THREAD

**Issue by bellasmith121995** [mtmorgan/DirichletMultinomial#6]
Hello, I am following the DMM tutorial here: https://microbiome.github.io/tutorials/DMM.html

I keep getting

``` fit
[[1]]
class: DMN 
k: 1 
samples x taxa: 7225 x 61 
Laplace: NaN BIC: NaN AIC: NaN 

[[2]]
class: DMN 
k: 2 
samples x taxa: 7225 x 61 
Laplace: NaN BIC: NaN AIC: NaN 

[[3]]
class: DMN 
k: 3 
samples x taxa: 7225 x 61 
Laplace: NaN BIC: NaN AIC: NaN 

[[4]]
class: DMN 
k: 4 
samples x taxa: 7225 x 61 
Laplace: NaN BIC: NaN AIC: NaN 

[[5]]
class: DMN 
k: 5 
samples x taxa: 7225 x 61 
Laplace: NaN BIC: NaN AIC: NaN 

[[6]]
class: DMN 
k: 6 
samples x taxa: 7225 x 61 
Laplace: NaN BIC: NaN AIC: NaN 
```

I make there are no columns or rows that only have zeros and no matter what I get this result. What could be causing this?  I also have tried with a small pseudocount and got the same results.

**Comment by mtmorgan** [comment]
The package vignette `browseVignettes(package="DirichletMultinomial")` has for instance
```
fl <- system.file(package="DirichletMultinomial", "extdata", "Twins.csv")
count <- t(as.matrix(read.csv(fl, row.names=1)))
dmn(count, 2, verbose = TRUE)
```
with output
```
dmn, k=2
  Soft kmeans
    iteration 10 change 0.000472
    iteration 20 change 0.000024
    iteration 30 change 0.000001
  Expectation Maximization setup
  Expectation Maximization
    iteration 10 change 0.068541
    iteration 20 change 0.000015
  Hessian
class: DMN
k: 2
samples x taxa: 278 x 130
Laplace: 38872.71 BIC: 39588.93 AIC: 39115.53
```
Is this what you have?  If so it is some unique property of your data. It might be the large number of samples so perhaps subset or collapse, or collinearity of the count matrix, or...? Maybe some basic diagnostics would help, e.g., `hist(log10(count))` especially in comparison to the sample data set, or subsampling rows / columns to a smaller matrix to investigate... I'm not really sure what to suggest without your count matrix. If you'd like to share that with me I could take a further look...

**Comment by Mattie-J** [comment]
Hello Martin,

I am using this package to assign enterotypes based on a gene count table (samples x taxa=1982 x 148) and ran into the same issue.

Following your suggestion, I randomly subsampled 300 rows from the given df, with missing values and constant columns removed (as was done for the total population). The subset of gene counts follows a extremely right-skewed distribution, which is similar to that of the example data you provided. 

My output seems to be aligned with your example output, except that there was nothing generated for Laplace, AIC and BIC at the end of k=2, 3, 4, etc. 
![Screenshot 2024-02-13 at 16 06 17](https://github.com/mtmorgan/DirichletMultinomial/assets/73783709/dccb573f-802f-4e5f-8266-5d2b574e2ff7)

Then by calling `lplc <- base::sapply(fit, DirichletMultinomial::laplace)` (also for `aic` and `bic`), it returned `NaN` for all of them.

Thank you if you could please advise on it!

p.s., Just got a bit confused because it used to work well for another dataset at my hand (dim: ~800x200, passing all the checks suggested above)..

**Comment by mtmorgan** [comment]
Can you provide a (sample) of your data that reproduces the problem?

**Comment by elmonten** [comment]
How did everyone solve this issue in the end?

**Comment by mtmorgan** [comment]
Did you try the steps in the comment https://github.com/mtmorgan/DirichletMultinomial/issues/6#issuecomment-1239797089 ? Can you share your data, so that I can investigate this more closely?

**Comment by elmonten** [comment]
Hi, thanks for your quick response. Yes, I have tried those steps.

- Filtering the 0s. Min_abundance of 0.001 and prevalence at 10%. (I'm working at species level, hence the very low minumum abundance)
- My original data has 185 sample by 79 species, but I did a subset of 16 samples to prevent colinearity (there are multiple biological replicates and time points). However, I obtained the same result.
- Here's the histogram of the log10 counts: 

![image](https://github.com/user-attachments/assets/1b9a8ee0-16ad-470a-af7a-21860eafd5d0)

**Comment by mtmorgan** [comment]
I really need access to your raw data (or, better, a minimum subset that reproduces the problem) in order to help further; you could for instance send me a link or even the data to the email address in my github profile.

**Comment by elmonten** [comment]
I found the solution. Since I was using species relative abundance, there were many values below 0.01 and that caused the NaNs (inspired by[ this other github issue ](https://github.com/numpy/numpy/issues/24210)). Multiplying the matrix by 100 solved the NaNs.

**Comment by mtmorgan** [comment]
Thanks for following through with your sample data and posting your solution.

The software assumes that the input is actual counts; it's not clear how you computed relative abundance, and whether transforming by multiplying by 100 is a reasonable practice. I'd encourage you to use the original counts.

**Comment by elmonten** [comment]
I followed [this tutorial](https://microbiome.github.io/tutorials/DMM.html)  where they transform the counts using `microbiome::transform(pseq, "compositional")`, thus I performed the same. However, I have just realized in the paper by [Holmes _et al_](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0030126) is stated in one line:
>  [...] for a single Dirichlet the posterior is itself a Dirichlet with parameters obtained by summing the **observed counts** and the Dirichlet parameters, [...]

Thus, I am a bit confused about how to proper pre-process the data (I do not have a strong mathematical background).

**Comment by mtmorgan** [comment]
The code coerces inputs to integer, following Homes et al. and really was developed expecting counts as input. Maybe @antagomir can provide some insight.

**Comment by antagomir** [comment]
@elmonten our tutorial that you cite is using compositional transformation only to determine which taxa are prevalent (or "not so rare"; pseq.comp data object). Then this set of taxa is used to subset the original count table (pseq) with prune_taxa function, and this subset of the count data is provided as input to DMM function (dmn) - so in fact  the input to DMM is also here count data, not relative abundance data.

Some taxonomic profiles only provide relative abundance data, then that might be a problem. 

In general we do not actively develop/support the phyloseq-based workflows any more as we switched to the TreeSummarizedExperiment-based framework for microbiome analysis. That provides some added capabilities for dealing with alternative assays (like counts and relabundances).
